export enum Designation {
  'Software Engineering Intern' = 'INTERN',
  'Software Engineer Trainee' = 'TRAINEE',
  'Assistant Software Development Engineer' = 'ASDE',
  'Software Development Engineer 1' = 'SDE1',
  'Software Development Engineer 2' = 'SDE2',
  'Software Development Engineer 3' = 'SDE3',
  'Infrastructure Manager' = 'IT',
  'Software Architect' = 'ARCHITECT',
  'Project Manager' = 'PM',
  'Team Lead' = 'TL',
  'Human Resource' = 'HR',
  'Chief Technology Officer' = 'CTO',
  'Finance Overseer' = 'FO',
}
